### ISSUE TITLE
TOML syntax plugin table arrays colored improperly

### ISSUE THREAD

**Issue by asleeves** [lite-xl/lite-xl-plugins#537]
The syntax for defining an array of tables:
```toml
[[people]]
name = "Person"
age = 35

[[people]]
name = "Other Person"
age = 72
```
renders improperly when using the TOML plugin:

![Image](https://github.com/user-attachments/assets/08ca783c-0eaa-4bbf-8cb0-0f6548e9ef9d)
